apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubedoom
  name: kubedoom
spec:
   hostNetwork: true
   containers:
   - image: storaxdev/kubedoom:0.5.0
     name: kubedoom
     ports:
     - containerPort: 5900
       protocol: TCP
   
    
